# Production Streamlit Secrets Configuration
# Copy this content to your Streamlit Cloud secrets

# Replace with your actual Railway backend URL after deployment
BACKEND_URL = "https://your-railway-backend.railway.app"

# Example Railway URL format:
# BACKEND_URL = "https://flowchat-backend-production.up.railway.app"