name: Wake Streamlit App

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes to prevent Streamlit sleep
  workflow_dispatch: # Allows manual triggering

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Initial wake up ping
        run: |
          echo " Waking up Streamlit app at $(date)"
          curl -I "https://flowchat-ai.streamlit.app"
          echo "Initial ping completed"
      
      - name: Health check with retry
        run: |
          FRONTEND_URL="https://flowchat-ai.streamlit.app"
          MAX_RETRIES=3
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            response=$(curl -s -o /dev/null -w "%{http_code}" "$FRONTEND_URL")
            
            if [ $response -eq 200 ]; then
              echo " App is healthy (HTTP $response) on attempt $((RETRY_COUNT + 1))"
              break
            else
              RETRY_COUNT=$((RETRY_COUNT + 1))
              echo " App returned HTTP $response on attempt $RETRY_COUNT"
              if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                echo "Retrying in 10 seconds..."
                sleep 10
              fi
            fi
          done
      
      - name: Multiple pings for sustained activity
        run: |
          FRONTEND_URL="https://flowchat-ai.streamlit.app"
          
          echo " Sending multiple pings to ensure activity..."
          for i in {1..3}; do
            echo "Ping $i of 3..."
            curl -s -o /dev/null "$FRONTEND_URL"
            if [ $i -lt 3 ]; then
              sleep 5
            fi
          done
          
          echo " All pings completed successfully at $(date)"