# Streamlit Secrets Configuration
# Update BACKEND_URL with your actual Railway deployment URL

[default]
BACKEND_URL = "https://your-railway-url.railway.app"

# After deploying to Railway, replace the URL above with your actual Railway app URL
# Example: BACKEND_URL = "https://floatchat-ai-production.railway.app"

# For local development, you can also add:
# BACKEND_URL_LOCAL = "http://localhost:8000"